# Generated by Django 5.2.8 on 2025-11-28 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='joined_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
