# Generated by Django 5.2.8 on 2025-11-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_alter_customuser_tg_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tg_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
