# Generated by Django 5.2.8 on 2025-11-29 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_alter_customuser_chat_id_alter_customuser_tg_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='joined_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
