# Generated by Django 5.2.8 on 2025-11-29 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0005_alter_eventmodel_joined_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='joined_users',
            field=models.ManyToManyField(blank=True, related_name='joined_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
